language: node_js
node_js:
  - stable
cache:
  - directories:
      - node_modules
branches:
  only:
    - source
script:
  - npm i
  - npm build
after_script:
  - cd build
  - git init
  - git config user.name "DongyunLee"
  - git config user.email "dongyunli619@gmail.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@github.com/novoland-game/novoland-game.github.io.git" master:master